import { Agent, AgentGroup, BlueprintTask, IndustryTemplate, PlanConfig, User } from '../types';

export const ADMIN_USER: User = {
  id: 'admin-uuid-1',
  email: 'damoneward38@gmail.com',
  name: 'Damone Ward (Admin)',
  role: 'admin',
  plan: 'enterprise',
  createdAt: '2026-01-15T08:00:00Z',
};

export const PLANS: PlanConfig[] = [
  {
    name: 'free',
    label: 'Free Sandbox',
    monthlyPrice: 0,
    annualPrice: 0,
    price: 0,
    billingPeriod: '30-day sandbox trial',
    description: 'Zero-cost friction drop for testing and evaluation (CLI, SDK, 8 modalities, 50% docs, 40 agents).',
    tagline: '1-day quick-tests; 403 drama block after 30 days',
    features: [
      '1-day quick-tests (CLI, SDK, all 8 calling modalities)',
      '50% of 177 documentation books & tool guides',
      '20% of agent swarm (≈ 40 micro-VM agents)',
      '30 days of immutable audit log data',
      'Strict 403 upgrade-needed drama block after 30 days',
      'Community Slack & local sandbox evaluation',
    ],
    scanMinutes: '30 min/day',
    customTemplates: '1 pre-built template',
    securityAgentsCount: 40,
    agentPercentage: '20% (≈ 40 agents)',
    targetVerticals: ['DevOps Testing', 'Early Prototypes', 'Academic Labs'],
    sla: 'Community Support',
  },
  {
    name: 'standard',
    label: 'T1 – Essentials',
    monthlyPrice: 250,
    annualPrice: 3000,
    price: 250,
    billingPeriod: 'per month ($3k/yr)',
    description: 'Low-price entry for small teams, developer pilots, and startup contracts.',
    tagline: '$250/mo or $3,000/yr — 20% agents, 100% docs & 1-hr on-prem SLA',
    features: [
      '20% of agent swarm (≈ 40 production agents)',
      '100% of 177 documentation books & public inventories',
      'Email support with guaranteed 4-hour response',
      '1-hour SLA (on-premises deployment)',
      'Cloud and local air-gapped deployment guides',
      'Removal of demo API throttle on all 8 modalities',
      'Target verticals: Banking, Retail, Medical, Smart-Home pilots',
    ],
    scanMinutes: 'Unlimited daily',
    customTemplates: '5 custom templates',
    securityAgentsCount: 40,
    agentPercentage: '20% (≈ 40 agents)',
    targetVerticals: ['Banking Pilots', 'Retail & E-Com', 'Medical Clinics', 'Smart-Home IoT'],
    sla: '1-hour SLA / 4-hr email response',
  },
  {
    name: 'pro',
    label: 'T2 – Pro',
    monthlyPrice: 1500,
    annualPrice: 18000,
    price: 1500,
    billingPeriod: 'per month ($18k/yr)',
    popular: true,
    description: 'High-throughput swarm execution for regulated mid-market firms.',
    tagline: '$1,500/mo or $18,000/yr — 70% agents, aggressive scans & 24-hr phone support',
    features: [
      '70% of agent swarm (≈ 140 parallel micro-VM agents)',
      'All 177 docs + complete Public Jev capability inventory',
      'Email + dedicated phone support (24-hr SLA)',
      '1-hour on-premise SLA guarantee',
      'Advanced high-bandwidth API (no throttling)',
      'Aggressive penetration testing & vulnerability hunting',
      'White-label branding optional upgrade path',
      'Target verticals: Banking, FinTech, Legal, Health',
    ],
    scanMinutes: 'Unlimited aggressive',
    customTemplates: '25 custom templates',
    securityAgentsCount: 140,
    agentPercentage: '70% (≈ 140 agents)',
    targetVerticals: ['Banking', 'FinTech', 'Law & Legal Defense', 'Healthcare & Pharma'],
    sla: '1-hour SLA / 24-hr phone & email',
  },
  {
    name: 'enterprise',
    label: 'T3 – Enterprise',
    monthlyPrice: 4500,
    annualPrice: 54000,
    price: 4500,
    billingPeriod: 'per month ($54k/yr)',
    description: 'Full-scale, enterprise-grade 200-core swarm with 24/7 dedicated on-prem support.',
    tagline: '$4,500/mo or $54,000/yr — 100% of agents (all 200), full SLA & custom branding',
    features: [
      '100% of agents (full 200-core swarm: 100 Security + 100 Creator)',
      'Complete 177 documentation books, toolsets & master guides',
      'Full SLA (1-hour response, 24-hr fallback guarantee)',
      '24/7 on-premise dedicated incident response support',
      'Managed-service add-on available',
      'Custom White-Label auto-gathered branding',
      'Air-gapped SCIF & zero-egress hardware compliance',
      'Target verticals: Insurance, Gov, Smart-Grid, Energy, Education, Media',
    ],
    scanMinutes: 'Continuous 24/7 Swarm',
    customTemplates: 'Unlimited A-to-Z templates',
    securityAgentsCount: 200,
    agentPercentage: '100% (all 200 agents)',
    targetVerticals: ['Insurance', 'Federal Gov & Defense', 'Smart-Grid & Energy', 'Education', 'Media'],
    sla: '24/7 on-premise / 1-hr SLA',
  },
];

// Target 12 Verticals Combo (3 per quarter)
export interface TargetVerticalInfo {
  no: number;
  vertical: string;
  quarter: string;
  tamEstimate: string;
  avgTco: string;
  complianceKey: string;
  description: string;
  iconName: string;
}

export const TARGET_VERTICALS_12: TargetVerticalInfo[] = [
  {
    no: 1,
    vertical: 'Banking / FinTech',
    quarter: 'Q1',
    tamEstimate: '$24M',
    avgTco: '$18k–$54k/yr',
    complianceKey: 'SEC 17a-4 / GLBA / FINRA 2210',
    description: 'Zero-egress transaction monitoring, SWIFT isolation, and algorithmic trade audit trails.',
    iconName: 'Landmark',
  },
  {
    no: 2,
    vertical: 'Health & MedTech',
    quarter: 'Q1',
    tamEstimate: '$19M',
    avgTco: '$18k–$54k/yr',
    complianceKey: 'HIPAA / FDA 21 CFR Part 11',
    description: 'Clinical trial patient privacy, cryptographic formula locking, and EHR data vault protection.',
    iconName: 'HeartPulse',
  },
  {
    no: 3,
    vertical: 'Law & Legal',
    quarter: 'Q1',
    tamEstimate: '$14M',
    avgTco: '$18k/yr',
    complianceKey: 'ABA Model Rule 1.6(c) Privilege',
    description: 'Zero-knowledge brief analysis, deposition confidentiality, and offline statutory citation.',
    iconName: 'Scale',
  },
  {
    no: 4,
    vertical: 'Insurance',
    quarter: 'Q2',
    tamEstimate: '$16M',
    avgTco: '$54k/yr',
    complianceKey: 'NAIC / SOC 2 Type II',
    description: 'Underwriting risk models, automated fraud anomaly detection, and claims ledgering.',
    iconName: 'ShieldCheck',
  },
  {
    no: 5,
    vertical: 'IoT & OT',
    quarter: 'Q2',
    tamEstimate: '$12M',
    avgTco: '$18k–$54k/yr',
    complianceKey: 'IEC 62443 / CISA Goals',
    description: 'Industrial sensor sentinels, CAN bus hardware inspection, and SCADA firmware auditing.',
    iconName: 'Cpu',
  },
  {
    no: 6,
    vertical: 'Retail & E-Commerce',
    quarter: 'Q2',
    tamEstimate: '$11M',
    avgTco: '$3k–$18k/yr',
    complianceKey: 'PCI-DSS v4.0 / GDPR',
    description: 'Checkout pipeline protection, catalog AI tagging, and Stripe webhook synchronization.',
    iconName: 'ShoppingCart',
  },
  {
    no: 7,
    vertical: 'Media & Streaming',
    quarter: 'Q3',
    tamEstimate: '$15M',
    avgTco: '$18k–$54k/yr',
    complianceKey: 'DMCA / DRM Widevine / FairPlay',
    description: 'Distributed transcoding, cryptographic watermarking, and global edge cache invalidation.',
    iconName: 'Film',
  },
  {
    no: 8,
    vertical: 'Gaming / Esports',
    quarter: 'Q3',
    tamEstimate: '$8M',
    avgTco: '$3k–$18k/yr',
    complianceKey: 'Anti-Cheat / COPPA',
    description: 'Low-latency server telemetry parsing, anti-tamper client sealing, and microtransaction audit.',
    iconName: 'Gamepad2',
  },
  {
    no: 9,
    vertical: 'Public-Sector / Gov',
    quarter: 'Q3',
    tamEstimate: '$28M',
    avgTco: '$54k/yr',
    complianceKey: 'FISMA High / CJIS / ITAR',
    description: 'Sovereign soil data residency, classified routing, FOIA redaction vaults, and defense SCIFs.',
    iconName: 'Building',
  },
  {
    no: 10,
    vertical: 'Education / EdTech',
    quarter: 'Q4',
    tamEstimate: '$7M',
    avgTco: '$3k–$18k/yr',
    complianceKey: 'FERPA / COPPA',
    description: 'Student PII containment, AI assignment plagiarism checking, and offline campus LLM nodes.',
    iconName: 'GraduationCap',
  },
  {
    no: 11,
    vertical: 'Travel & Hospitality',
    quarter: 'Q4',
    tamEstimate: '$6M',
    avgTco: '$3k–$18k/yr',
    complianceKey: 'PCI-DSS / GDPR Cross-Border',
    description: 'Global reservation booking APIs, passport data tokenization, and multi-currency ledgers.',
    iconName: 'Plane',
  },
  {
    no: 12,
    vertical: 'Energy / Utilities',
    quarter: 'Q4',
    tamEstimate: '$22M',
    avgTco: '$54k/yr',
    complianceKey: 'NERC CIP-002 through CIP-014',
    description: 'Nuclear and power grid air-gap sentinels behind physical unidirectional data diodes.',
    iconName: 'Zap',
  },
];

// White-Label (Indigo) Offer Details
export const WHITE_LABEL_OFFER = {
  tierName: 'White-Label (Indigo)',
  singleTimeLicense: 110000,
  annualMaintenance: 60000,
  monthlyEquivalent: 5000,
  earlyAdopterDiscount: 0.15, // 15% discount for 30-day signing
  discountedSingleTime: 93500,
  targetAudience: 'B2B OEM partners, Independent Software Vendors (ISVs), Enterprise Systems Integrators',
  includes: [
    'Full 3-Pillar Stack (Sapphire, Open-Jev, Tempest — all 200 agents)',
    'Complete Custom Brand Kit (Custom UI, logo, custom domain, white-label docs)',
    '1-Year Maintenance & Upgrade Lease with 24-hr on-site SLA',
    'One-Time Cryptographic Key Integration & Signing Ceremony',
    'Full rights to re-brand and embed into proprietary product suites',
    '15% First-Year Discount for locking in the 30-day trial agreement',
  ],
  clauses: [
    { title: '1. License Clause', text: 'All 200-core underlying agents remain the proprietary intellectual property of Neural Core / Taḥnīʿ Hâzoo.' },
    { title: '2. Service Clause', text: 'Maintenance, security patches, upgrades, and 24-h SLA support guaranteed for 12 months, renewable annually.' },
    { title: '3. Security Clause', text: 'Audit logger is immutable; application must run strictly on customer on-premises or sovereign cloud hardware.' },
    { title: '4. Resale Clause', text: 'OEM partner may re-brand and distribute to end-clients, but cannot unbundle or resell the raw underlying core as their own.' },
  ],
};

// 10-Week Implementation Timeline
export interface TimelineWeek {
  week: number;
  milestone: string;
  deliverable: string;
  status: 'completed' | 'in_progress' | 'scheduled';
}

export const IMPLEMENTATION_TIMELINE_10WEEKS: TimelineWeek[] = [
  { week: 1, milestone: 'Draft licenses & feature-gate middleware', deliverable: 'draft.py (middleware checks)', status: 'completed' },
  { week: 2, milestone: 'Release API & 3-tier endpoints', deliverable: 'api_v3.py (REST endpoints)', status: 'completed' },
  { week: 3, milestone: 'Create Free Sandbox package', deliverable: 'sandbox.tar.gz (40-agent image)', status: 'completed' },
  { week: 4, milestone: 'Implement White-Label agreement wizard', deliverable: 'wizard.html (Lead form & contract)', status: 'completed' },
  { week: 5, milestone: 'Add Stripe checkout integration', deliverable: 'stripe_checkout.js (Setup Intents & Connect)', status: 'completed' },
  { week: 6, milestone: 'Test edge-case 403 "blocked" requests', deliverable: 'integration.test.js (telemetry queue)', status: 'completed' },
  { week: 7, milestone: 'Publish pricing page & docs', deliverable: 'pricing.html (dual monthly/annual)', status: 'completed' },
  { week: 8, milestone: 'Outreach to 12 target verticals', deliverable: 'email_list.csv (3 verticals/quarter)', status: 'in_progress' },
  { week: 9, milestone: 'First 3 pilot contracts signed', deliverable: '3x_contract.pdf (Banking/Health/Legal)', status: 'scheduled' },
  { week: 10, milestone: 'Level-up to Enterprise on Day 1', deliverable: 'enterprise_close.docx (multi-site rollouts)', status: 'scheduled' },
];

// Margins & TCO Comparison
export const PRICING_MARGINS_TCO = [
  { tier: 'Free Sandbox', tco: '$0', arr: '$0', margin: '–', conversionHook: '10% trial → 1-in-10 Pro → 5% Enterprise' },
  { tier: 'T1 – Essentials', tco: '$3,000/yr ($250/mo)', arr: '$3k per client', margin: '70%', conversionHook: 'Low-friction entry for startups & pilot projects' },
  { tier: 'T2 – Pro', tco: '$18,000/yr ($1,500/mo)', arr: '$18k per client', margin: '65%', conversionHook: 'High adoption in Banking, FinTech, Legal & Health' },
  { tier: 'T3 – Enterprise', tco: '$54,000/yr ($4,500/mo)', arr: '$54k per client', margin: '55%', conversionHook: 'Full-scale defense, gov, energy & media deployments' },
  { tier: 'White-Label (Indigo)', tco: '$110k one-time + $60k/yr ($5k/mo)', arr: '$60k/yr recurring + $110k', margin: '50%', conversionHook: 'OEM / ISV leverage: $110M TAM at 2% = $2M ARR' },
];

// Helper to generate 200 agents (10 groups x 20 agents)
export function generate200Agents(): Agent[] {
  const groupsConfig: { group: AgentGroup; category: 'security' | 'business'; functionName: string; roleLabel: string }[] = [
    { group: 'A', category: 'security', functionName: 'scanCVE', roleLabel: 'CVE Vulnerability Scanner' },
    { group: 'B', category: 'security', functionName: 'wafAudit', roleLabel: 'Perimeter & WAF Sentinel' },
    { group: 'C', category: 'security', functionName: 'sandboxExec', roleLabel: 'Runtime Sandbox Sanitizer' },
    { group: 'D', category: 'security', functionName: 'policyAudit', roleLabel: 'MFA & Compliance Policy Auditor' },
    { group: 'E', category: 'security', functionName: 'autoPatch', roleLabel: 'Auto-Remediation & Patch Engine' },
    { group: 'F', category: 'business', functionName: 'transcode', roleLabel: 'Ingestion & Transcode Pipeline' },
    { group: 'G', category: 'business', functionName: 'metadataTagging', roleLabel: 'Catalog & Metadata AI Tagger' },
    { group: 'H', category: 'business', functionName: 'drmEmbedding', roleLabel: 'DRM & Cryptographic Licensing' },
    { group: 'I', category: 'business', functionName: 'billingHooks', roleLabel: 'Billing & CRM Hook Synchronizer' },
    { group: 'J', category: 'business', functionName: 'edgeDistribution', roleLabel: 'Global Edge & CDN Orchestrator' },
  ];

  const agents: Agent[] = [];
  groupsConfig.forEach(({ group, category, functionName, roleLabel }) => {
    for (let i = 1; i <= 20; i++) {
      const padNum = i.toString().padStart(2, '0');
      const id = `agent-${group.toLowerCase()}-${padNum}`;
      agents.push({
        id,
        groupName: group,
        category,
        functionName,
        roleLabel: `${roleLabel} #${padNum}`,
        status: (i === 18 && group === 'C') ? 'busy' : (i === 20 && group === 'E') ? 'busy' : 'online',
        lastSeen: new Date(Date.now() - Math.floor(Math.random() * 60000)).toISOString(),
        cpuUsage: Number((12 + Math.random() * 25).toFixed(1)),
        memoryUsage: Number((35 + Math.random() * 30).toFixed(1)),
        latencyMs: Math.floor(18 + Math.random() * 45),
        totalJobsProcessed: Math.floor(120 + Math.random() * 450),
      });
    }
  });

  return agents;
}

// Pre-built task library
export const TASK_LIBRARY: BlueprintTask[] = [
  // Business Tasks
  { id: 't01', name: 'Media Ingestion & Audio Transcoding', group: 'F', function: 'transcode', type: 'business', planLocked: false, description: 'High-speed distributed transcoding and adaptive bitrate chunking.', requiredTier: 'free' },
  { id: 't02', name: 'AI Metadata & Semantic Tagging', group: 'G', function: 'metadataTagging', type: 'business', planLocked: false, description: 'Automated tag extraction, SEO schemas, and category taxonomies.', requiredTier: 'free' },
  { id: 't03', name: 'Digital Rights Management (DRM) Seal', group: 'H', function: 'drmEmbedding', type: 'business', planLocked: true, description: 'Watermark stamping and Widevine/FairPlay token encryption.', requiredTier: 'standard' },
  { id: 't04', name: 'Stripe & Billing Ledger Synchronizer', group: 'I', function: 'billingHooks', type: 'business', planLocked: false, description: 'Webhook processing for recurring invoices, taxes, and customer MRR.', requiredTier: 'free' },
  { id: 't05', name: 'Worldwide Edge CDN Deployer', group: 'J', function: 'edgeDistribution', type: 'business', planLocked: true, description: 'Zero-downtime cache invalidation across 180+ global edge pops.', requiredTier: 'standard' },
  
  // Security Tasks
  { id: 's01', name: 'CI/CD Vulnerability & CVE Scan', group: 'A', function: 'scanCVE', type: 'security', planLocked: false, description: 'Static code and dependency scanning against CVE databases.', requiredTier: 'free' },
  { id: 's02', name: 'Perimeter WAF & Port Audit', group: 'B', function: 'wafAudit', type: 'security', planLocked: false, description: 'Ingress route scanning and network boundary verification.', requiredTier: 'free' },
  { id: 's03', name: 'Runtime Sandbox Trap & Container Analysis', group: 'C', function: 'sandboxExec', type: 'security', planLocked: true, description: 'Dynamic execution in isolated Firecracker micro-VMs.', requiredTier: 'standard' },
  { id: 's04', name: 'MFA & Zero-Trust Access Policy Audit', group: 'D', function: 'policyAudit', type: 'security', planLocked: true, description: 'Authentication posture check, token rotation, and IAM policy analysis.', requiredTier: 'standard' },
  { id: 's05', name: 'Autonomous Patch Engine & Hotfix Rollout', group: 'E', function: 'autoPatch', type: 'security', planLocked: true, description: 'Automated pull-request generation and verified hotfix injector.', requiredTier: 'enterprise' },
  { id: 's06', name: 'Air-Gapped Zero-Egress Network Enforcer', group: 'C', function: 'sandboxExec', type: 'security', planLocked: true, description: 'Enforces strict local isolation; drops all outbound packets to prevent confidential leaks.', requiredTier: 'enterprise' },
  { id: 's07', name: 'WORM Immutable Audit Archiver (SEC 17a-4 / FDA)', group: 'D', function: 'policyAudit', type: 'security', planLocked: true, description: 'Writes Write-Once-Read-Many cryptographic SHA-256 blocks for federal compliance audits.', requiredTier: 'enterprise' },
  { id: 's08', name: 'Classified PII & Privilege Sanitizer', group: 'B', function: 'wafAudit', type: 'security', planLocked: true, description: 'Deep redaction for attorney-client discovery, patient PHI, and classified defense data.', requiredTier: 'standard' },
];

export const INDUSTRY_TEMPLATES: IndustryTemplate[] = [
  // HIGH-SECURITY & REGULATED INDUSTRIES (ZERO-EGRESS)
  {
    id: 'ind-banking-tier1',
    name: 'Financial Institutions & Tier-1 Banks',
    code: 'Banking-Financial',
    category: 'Banking & Global Finance',
    iconName: 'Landmark',
    description: 'Air-gapped on-premise execution, GLBA & SEC 17a-4 WORM audit logs, SWIFT payment transaction monitoring, and zero-leakage trade operations.',
    defaultTasks: [TASK_LIBRARY[3], TASK_LIBRARY[5], TASK_LIBRARY[6], TASK_LIBRARY[7], TASK_LIBRARY[8], TASK_LIBRARY[9]],
    defaultStorage: 'On-Premises HSM-Encrypted High-Availability PostgreSQL',
    defaultPayment: 'Fedwire / SWIFT / Stripe Treasury Direct',
    recommendedCompliance: ['SEC Rule 17a-4', 'GLBA Safeguards Rule', 'PCI-DSS Level 1', 'FINRA Rule 2210', 'SOX 404'],
  },
  {
    id: 'ind-law-defense',
    name: 'Law Firms, Litigation & Corporate Defense',
    code: 'LawFirms-Litigation',
    category: 'High-Confidentiality Legal',
    iconName: 'Scale',
    description: 'Absolute attorney-client privilege protection, local offline Qwen statutory reasoning, zero external cloud transmission of confidential trial briefs.',
    defaultTasks: [TASK_LIBRARY[1], TASK_LIBRARY[5], TASK_LIBRARY[6], TASK_LIBRARY[7], TASK_LIBRARY[8]],
    defaultStorage: 'Local Air-Gapped Zero-Knowledge Document Repository',
    defaultPayment: 'IOLTA Trust Accounting / Clio Legal Invoicing',
    recommendedCompliance: ['ABA Model Rule 1.6(c)', 'State Bar Ethics Opinions', 'SOC 2 Type II', 'ISO 27001'],
  },
  {
    id: 'ind-defense-military',
    name: 'Defense, Armed Forces & Naval Command',
    code: 'Defense-Military-Naval',
    category: 'Defense & Armed Forces',
    iconName: 'ShieldAlert',
    description: 'Army bases, naval command vessels, and Pentagon installations: SCIF-ready local Ollama reasoning, CAN bus hardware analysis, and zero cloud telemetry.',
    defaultTasks: [TASK_LIBRARY[0], TASK_LIBRARY[4], TASK_LIBRARY[5], TASK_LIBRARY[6], TASK_LIBRARY[7], TASK_LIBRARY[8]],
    defaultStorage: 'FIPS 140-3 Hardware-Encrypted Secure Storage Node',
    defaultPayment: 'Government Disbursing Office / DoD WAWF',
    recommendedCompliance: ['DoD FedRAMP High', 'ITAR (International Traffic in Arms)', 'CMMC Level 3', 'NIST SP 800-171'],
  },
  {
    id: 'ind-gov-intel',
    name: 'Federal Government & Intelligence Agencies',
    code: 'Gov-Intelligence',
    category: 'Federal & Intelligence',
    iconName: 'Building',
    description: 'Civilian and intelligence agency coordination: classified routing, automated FOIA redaction vaults, CJIS crime reporting encryption, and strict data sovereignty.',
    defaultTasks: [TASK_LIBRARY[1], TASK_LIBRARY[5], TASK_LIBRARY[6], TASK_LIBRARY[7], TASK_LIBRARY[8]],
    defaultStorage: 'FedRAMP High Validated On-Premises Cluster',
    defaultPayment: 'Federal Financial Management System (FFMS)',
    recommendedCompliance: ['FISMA High', 'CJIS Security Policy', 'NIST SP 800-53 Rev 5', 'FedRAMP High Baseline'],
  },
  {
    id: 'ind-fda-pharma',
    name: 'FDA, Food Administration & Clinical Pharma',
    code: 'FDA-Pharma-Trials',
    category: 'Food, Drug & Clinical Trials',
    iconName: 'HeartPulse',
    description: 'FDA regulated clinical trials, pharmaceutical formula locking, 21 CFR Part 11 electronic records, and strict prevention of proprietary drug recipe leaks.',
    defaultTasks: [TASK_LIBRARY[1], TASK_LIBRARY[3], TASK_LIBRARY[5], TASK_LIBRARY[6], TASK_LIBRARY[8]],
    defaultStorage: 'Validated 21 CFR Part 11 Compliant Cryptographic Data Vault',
    defaultPayment: 'Clinical CRO Trial Billing & Sponsor Milestone Gateway',
    recommendedCompliance: ['FDA 21 CFR Part 11', 'Good Clinical Practice (GCP)', 'HIPAA Security Rule', 'GxP Computer System Validation'],
  },
  {
    id: 'ind-critical-infra',
    name: 'Critical Infrastructure & Energy Grids',
    code: 'Critical-Infrastructure',
    category: 'National Critical Infrastructure',
    iconName: 'Zap',
    description: 'Nuclear facilities, municipal water treatment, and electrical power grids: NERC CIP air-gapped monitoring, SCADA/PLC protocol sentinels, zero cloud risk.',
    defaultTasks: [TASK_LIBRARY[0], TASK_LIBRARY[4], TASK_LIBRARY[5], TASK_LIBRARY[6], TASK_LIBRARY[7], TASK_LIBRARY[8]],
    defaultStorage: 'Isolated Air-Gapped Industrial Historian Appliance',
    defaultPayment: 'Utility Rate-Base Billing / Industrial EDI',
    recommendedCompliance: ['NERC CIP-002 through CIP-014', 'CISA Cross-Sector Performance Goals', 'IEC 62443'],
  },
  {
    id: 'ind-media',
    name: 'Media & Streaming',
    code: 'Media-Streaming',
    category: 'Entertainment & Content',
    iconName: 'Film',
    description: 'Automated ingestion, DRM protection, dynamic ad markers, and global CDN delivery.',
    defaultTasks: [TASK_LIBRARY[0], TASK_LIBRARY[1], TASK_LIBRARY[2], TASK_LIBRARY[5], TASK_LIBRARY[8]],
    defaultStorage: 'S3-Compatible Object Store with Tiering',
    defaultPayment: 'Stripe Billing & Metered Usage API',
    recommendedCompliance: ['GDPR', 'SOC 2 Type II', 'DMCA Safe Harbor'],
  },
  {
    id: 'ind-fintech',
    name: 'FinTech & Neobank',
    code: 'FinTech-Banking',
    category: 'Finance & Banking',
    iconName: 'CreditCard',
    description: 'PCA-grade audit trails, PCI-DSS tokenization, real-time ledger consistency, and MFA.',
    defaultTasks: [TASK_LIBRARY[3], TASK_LIBRARY[5], TASK_LIBRARY[6], TASK_LIBRARY[7], TASK_LIBRARY[8], TASK_LIBRARY[9]],
    defaultStorage: 'PostgreSQL with End-to-End Columnar Encryption',
    defaultPayment: 'Plaid + Stripe Treasury API',
    recommendedCompliance: ['PCI-DSS Level 1', 'SOC 2 Type II', 'GLBA'],
  },
  {
    id: 'ind-health',
    name: 'Healthcare & Telehealth',
    code: 'Healthcare-Telehealth',
    category: 'Life Sciences & Medicine',
    iconName: 'HeartPulse',
    description: 'HIPAA-compliant ePHI vault, end-to-end patient messaging encryption, and access logs.',
    defaultTasks: [TASK_LIBRARY[1], TASK_LIBRARY[3], TASK_LIBRARY[5], TASK_LIBRARY[6], TASK_LIBRARY[8]],
    defaultStorage: 'HIPAA-BAA Compliant Cloud Storage',
    defaultPayment: 'Healthcare Merchant Gateway (Authorize.net)',
    recommendedCompliance: ['HIPAA BAA', 'HITECH Act', 'SOC 2 Type II'],
  },
  {
    id: 'ind-retail',
    name: 'Retail & E-Commerce',
    code: 'Retail-Ecommerce',
    category: 'Commerce & Direct-to-Consumer',
    iconName: 'ShoppingBag',
    description: 'High-volume inventory sync, cart abandonment recovery, fast checkout, and bot protection.',
    defaultTasks: [TASK_LIBRARY[1], TASK_LIBRARY[3], TASK_LIBRARY[4], TASK_LIBRARY[5], TASK_LIBRARY[6]],
    defaultStorage: 'Managed NoSQL Redis Cache + Aurora PostgreSQL',
    defaultPayment: 'Shopify Storefront API + Stripe Elements',
    recommendedCompliance: ['PCI-DSS', 'GDPR', 'CCPA'],
  },
  {
    id: 'ind-saas',
    name: 'B2B SaaS & Cloud',
    code: 'SaaS-B2B',
    category: 'Software & Technology',
    iconName: 'Layers',
    description: 'Multi-tenant database isolation, team RBAC hierarchies, audit log exports, and API keys.',
    defaultTasks: [TASK_LIBRARY[1], TASK_LIBRARY[3], TASK_LIBRARY[4], TASK_LIBRARY[5], TASK_LIBRARY[7], TASK_LIBRARY[8]],
    defaultStorage: 'Cloud SQL PostgreSQL + Multi-Region Replica',
    defaultPayment: 'Stripe Customer Portal + Paddle',
    recommendedCompliance: ['SOC 2 Type II', 'ISO 27001', 'GDPR'],
  },
  {
    id: 'ind-iot',
    name: 'IoT & Smart Devices',
    code: 'IoT-Industrial',
    category: 'Hardware & Edge',
    iconName: 'Cpu',
    description: 'Device fleet telemetry, mTLS certificate provisioning, OTA firmware sandboxes, and anomaly traps.',
    defaultTasks: [TASK_LIBRARY[0], TASK_LIBRARY[4], TASK_LIBRARY[5], TASK_LIBRARY[6], TASK_LIBRARY[7], TASK_LIBRARY[9]],
    defaultStorage: 'Time-Series InfluxDB + Cold Blob Archive',
    defaultPayment: 'Hardware License Gateway',
    recommendedCompliance: ['NIST SP 800-213', 'ISO 27001'],
  },
  {
    id: 'ind-logistics',
    name: 'Logistics & Supply Chain',
    code: 'Logistics-Fleet',
    category: 'Industrial & Freight',
    iconName: 'Truck',
    description: 'Real-time GPS route optimization, electronic bill of lading, and tamper-evident shipment ledgers.',
    defaultTasks: [TASK_LIBRARY[1], TASK_LIBRARY[3], TASK_LIBRARY[5], TASK_LIBRARY[6], TASK_LIBRARY[8]],
    defaultStorage: 'Distributed Geospatial TimescaleDB',
    defaultPayment: 'FreightPay ACH & Electronic Factoring',
    recommendedCompliance: ['C-TPAT Security', 'ISO 28000'],
  },
  {
    id: 'ind-realestate',
    name: 'Real Estate & PropTech',
    code: 'RealEstate-PropTech',
    category: 'Property & Facilities',
    iconName: 'Building',
    description: 'MLS listing syndication, electronic lease signing, escrow funds tracking, and tenant portal.',
    defaultTasks: [TASK_LIBRARY[1], TASK_LIBRARY[3], TASK_LIBRARY[5], TASK_LIBRARY[6], TASK_LIBRARY[8]],
    defaultStorage: 'Secure Document Vault with S3 Object Lock',
    defaultPayment: 'Dwolla ACH Tenant Payments',
    recommendedCompliance: ['Fair Housing Act', 'SOC 2 Type II'],
  },
  {
    id: 'ind-education',
    name: 'Education & EdTech',
    code: 'Education-EdTech',
    category: 'Academic & Learning',
    iconName: 'GraduationCap',
    description: 'FERPA-compliant student records, anti-plagiarism verification, video lectures, and grading rubrics.',
    defaultTasks: [TASK_LIBRARY[0], TASK_LIBRARY[1], TASK_LIBRARY[5], TASK_LIBRARY[6], TASK_LIBRARY[8]],
    defaultStorage: 'Encrypted Cloud Storage + LTI 1.3 Adapters',
    defaultPayment: 'Stripe Invoicing / University PO',
    recommendedCompliance: ['FERPA', 'COPPA', 'GDPR'],
  },
  {
    id: 'ind-legal',
    name: 'LegalOps & ContractTech',
    code: 'LegalTech-Contracts',
    category: 'Legal & Professional Services',
    iconName: 'Scale',
    description: 'Attorney-client privilege isolation, immutable redlining records, and redaction verification.',
    defaultTasks: [TASK_LIBRARY[1], TASK_LIBRARY[5], TASK_LIBRARY[6], TASK_LIBRARY[7], TASK_LIBRARY[8]],
    defaultStorage: 'Zero-Knowledge Encrypted Document Store',
    defaultPayment: 'IOLTA-Compliant Client Trust Billing',
    recommendedCompliance: ['ABA Model Rules', 'SOC 2 Type II', 'ISO 27001'],
  },
];
